const countryMeta = {
  Afghanistan: { slug: "Afghan_citizens", emoji: "🇦🇫" },
  Albania: { slug: "Albanian_citizens", emoji: "🇦🇱" },
  Algeria: { slug: "Algerian_citizens", emoji: "🇩🇿" },
  Andorra: { slug: "Andorran_citizens", emoji: "🇦🇩" },
  Angola: { slug: "Angolan_citizens", emoji: "🇦🇴" },
  "Antigua and Barbuda": { slug: "Antiguan_citizens", emoji: "🇦🇬" },
  Argentina: { slug: "Argentine_citizens", emoji: "🇦🇷" },
  Armenia: { slug: "Armenian_citizens", emoji: "🇦🇲" },
  Australia: { slug: "Australian_citizens", emoji: "🇦🇺" },
  Austria: { slug: "Austrian_citizens", emoji: "🇦🇹" },
  Azerbaijan: { slug: "Azerbaijani_citizens", emoji: "🇦🇿" },
  Bahamas: { slug: "Bahamian_citizens", emoji: "🇧🇸" },
  Bahrain: { slug: "Bahraini_citizens", emoji: "🇧🇭" },
  Bangladesh: { slug: "Bangladeshi_citizens", emoji: "🇧🇩" },
  Barbados: { slug: "Barbadian_citizens", emoji: "🇧🇧" },
  Belarus: { slug: "Belarusian_citizens", emoji: "🇧🇾" },
  Belgium: { slug: "Belgian_citizens", emoji: "🇧🇪" },
  Belize: { slug: "Belizean_citizens", emoji: "🇧🇿" },
  Benin: { slug: "Beninese_citizens", emoji: "🇧🇯" },
  Bhutan: { slug: "Bhutanese_citizens", emoji: "🇧🇹" },
  Bolivia: { slug: "Bolivian_citizens", emoji: "🇧🇴" },
  "Bosnia and Herzegovina": { slug: "Bosnian_citizens", emoji: "🇧🇦" },
  Botswana: { slug: "Botswanan_citizens", emoji: "🇧🇼" },
  Brazil: { slug: "Brazilian_citizens", emoji: "🇧🇷" },
  Brunei: { slug: "Bruneian_citizens", emoji: "🇧🇳" },
  Bulgaria: { slug: "Bulgarian_citizens", emoji: "🇧🇬" },
  "Burkina Faso": { slug: "Burkinabe_citizens", emoji: "🇧🇫" },
  Burundi: { slug: "Burundian_citizens", emoji: "🇧🇮" },
  "Cape Verde": { slug: "Cape_Verdean_citizens", emoji: "🇨🇻" },
  Cambodia: { slug: "Cambodian_citizens", emoji: "🇰🇭" },
  Cameroon: { slug: "Cameroonian_citizens", emoji: "🇨🇲" },
  Canada: { slug: "Canadian_citizens", emoji: "🇨🇦" },
  "Central African Republic": { slug: "Central_African_citizens", emoji: "🇨🇫" },
  Chad: { slug: "Chadian_citizens", emoji: "🇹🇩" },
  Chile: { slug: "Chilean_citizens", emoji: "🇨🇱" },
  China: { slug: "Chinese_citizens", emoji: "🇨🇳" },
  Colombia: { slug: "Colombian_citizens", emoji: "🇨🇴" },
  Comoros: { slug: "Comorian_citizens", emoji: "🇰🇲" },
  "Republic of the Congo": {
    slug: "Republic_of_the_Congo_citizens",
    emoji: "🇨🇬",
  },
  "Democratic Republic of the Congo": {
    slug: "Democratic_Republic_of_the_Congo_citizens",
    emoji: "🇨🇩",
  },
  "Costa Rica": { slug: "Costa_Rican_citizens", emoji: "🇨🇷" },
  "Côte d'Ivoire": { slug: "Ivorian_citizens", emoji: "🇨🇮" },
  Croatia: { slug: "Croatian_citizens", emoji: "🇭🇷" },
  Cuba: { slug: "Cuban_citizens", emoji: "🇨🇺" },
  Cyprus: { slug: "Cypriot_citizens", emoji: "🇨🇾" },
  "Czech Republic": { slug: "Czech_citizens", emoji: "🇨🇿" },
  Denmark: { slug: "Danish_citizens", emoji: "🇩🇰" },
  Djibouti: { slug: "Djiboutian_citizens", emoji: "🇩🇯" },
  Dominica: { slug: "Dominican_(Dominica)_citizens", emoji: "🇩🇲" },
  "Dominican Republic": { slug: "Dominican_(Republic)_citizens", emoji: "🇩🇴" },
  Ecuador: { slug: "Ecuadorian_citizens", emoji: "🇪🇨" },
  Egypt: { slug: "Egyptian_citizens", emoji: "🇪🇬" },
  "El Salvador": { slug: "Salvadoran_citizens", emoji: "🇸🇻" },
  "Equatorial Guinea": { slug: "Equatorial_Guinean_citizens", emoji: "🇬🇶" },
  Eritrea: { slug: "Eritrean_citizens", emoji: "🇪🇷" },
  Estonia: { slug: "Estonian_citizens", emoji: "🇪🇪" },
  Eswatini: { slug: "Swazi_citizens", emoji: "🇸🇿" },
  Ethiopia: { slug: "Ethiopian_citizens", emoji: "🇪🇹" },
  Fiji: { slug: "Fijian_citizens", emoji: "🇫🇯" },
  Finland: { slug: "Finnish_citizens", emoji: "🇫🇮" },
  France: { slug: "French_citizens", emoji: "🇫🇷" },
  Gabon: { slug: "Gabonese_citizens", emoji: "🇬🇦" },
  Gambia: { slug: "Gambian_citizens", emoji: "🇬🇲" },
  Georgia: { slug: "Georgian_citizens", emoji: "🇬🇪" },
  Germany: { slug: "German_citizens", emoji: "🇩🇪" },
  Ghana: { slug: "Ghanaian_citizens", emoji: "🇬🇭" },
  Greece: { slug: "Greek_citizens", emoji: "🇬🇷" },
  Grenada: { slug: "Grenadian_citizens", emoji: "🇬🇩" },
  Guatemala: { slug: "Guatemalan_citizens", emoji: "🇬🇹" },
  Guinea: { slug: "Guinean_citizens", emoji: "🇬🇳" },
  "Guinea-Bissau": { slug: "Bissau-Guinean_citizens", emoji: "🇬🇼" },
  Guyana: { slug: "Guyanese_citizens", emoji: "🇬🇾" },
  Haiti: { slug: "Haitian_citizens", emoji: "🇭🇹" },
  Honduras: { slug: "Honduran_citizens", emoji: "🇭🇳" },
  Hungary: { slug: "Hungarian_citizens", emoji: "🇭🇺" },
  Iceland: { slug: "Icelandic_citizens", emoji: "🇮🇸" },
  India: { slug: "Indian_citizens", emoji: "🇮🇳" },
  Indonesia: { slug: "Indonesian_citizens", emoji: "🇮🇩" },
  Iran: { slug: "Iranian_citizens", emoji: "🇮🇷" },
  Iraq: { slug: "Iraqi_citizens", emoji: "🇮🇶" },
  Ireland: { slug: "Irish_citizens", emoji: "🇮🇪" },
  Israel: { slug: "Israeli_citizens", emoji: "🇮🇱" },
  Italy: { slug: "Italian_citizens", emoji: "🇮🇹" },
  Jamaica: { slug: "Jamaican_citizens", emoji: "🇯🇲" },
  Japan: { slug: "Japanese_citizens", emoji: "🇯🇵" },
  Jordan: { slug: "Jordanian_citizens", emoji: "🇯🇴" },
  Kazakhstan: { slug: "Kazakhstani_citizens", emoji: "🇰🇿" },
  Kenya: { slug: "Kenyan_citizens", emoji: "🇰🇪" },
  Kiribati: { slug: "I-Kiribati_citizens", emoji: "🇰🇮" },
  Kuwait: { slug: "Kuwaiti_citizens", emoji: "🇰🇼" },
  Kyrgyzstan: { slug: "Kyrgyz_citizens", emoji: "🇰🇬" },
  Laos: { slug: "Lao_citizens", emoji: "🇱🇦" },
  Latvia: { slug: "Latvian_citizens", emoji: "🇱🇻" },
  Lebanon: { slug: "Lebanese_citizens", emoji: "🇱🇧" },
  Lesotho: { slug: "Basotho_citizens", emoji: "🇱🇸" },
  Liberia: { slug: "Liberian_citizens", emoji: "🇱🇷" },
  Libya: { slug: "Libyan_citizens", emoji: "🇱🇾" },
  Liechtenstein: { slug: "Liechtensteiner_citizens", emoji: "🇱🇮" },
  Lithuania: { slug: "Lithuanian_citizens", emoji: "🇱🇹" },
  Luxembourg: { slug: "Luxembourgish_citizens", emoji: "🇱🇺" },
  Madagascar: { slug: "Malagasy_citizens", emoji: "🇲🇬" },
  Malawi: { slug: "Malawian_citizens", emoji: "🇲🇼" },
  Malaysia: { slug: "Malaysian_citizens", emoji: "🇲🇾" },
  Maldives: { slug: "Maldivian_citizens", emoji: "🇲🇻" },
  Mali: { slug: "Malian_citizens", emoji: "🇲🇱" },
  Malta: { slug: "Maltese_citizens", emoji: "🇲🇹" },
  "Marshall Islands": { slug: "Marshallese_citizens", emoji: "🇲🇭" },
  Mauritania: { slug: "Mauritanian_citizens", emoji: "🇲🇷" },
  Mauritius: { slug: "Mauritian_citizens", emoji: "🇲🇺" },
  Mexico: { slug: "Mexican_citizens", emoji: "🇲🇽" },
  Micronesia: { slug: "Micronesian_citizens", emoji: "🇫🇲" },
  Moldova: { slug: "Moldovan_citizens", emoji: "🇲🇩" },
  Monaco: { slug: "Monegasque_citizens", emoji: "🇲🇨" },
  Mongolia: { slug: "Mongolian_citizens", emoji: "🇲🇳" },
  Montenegro: { slug: "Montenegrin_citizens", emoji: "🇲🇪" },
  Morocco: { slug: "Moroccan_citizens", emoji: "🇲🇦" },
  Mozambique: { slug: "Mozambican_citizens", emoji: "🇲🇿" },
  Myanmar: { slug: "Burmese_citizens", emoji: "🇲🇲" },
  Namibia: { slug: "Namibian_citizens", emoji: "🇳🇦" },
  Nauru: { slug: "Nauruan_citizens", emoji: "🇳🇷" },
  Nepal: { slug: "Nepalese_citizens", emoji: "🇳🇵" },
  Netherlands: { slug: "Dutch_citizens", emoji: "🇳🇱" },
  "New Zealand": { slug: "New_Zealander_citizens", emoji: "🇳🇿" },
  Nicaragua: { slug: "Nicaraguan_citizens", emoji: "🇳🇮" },
  Niger: { slug: "Nigerien_citizens", emoji: "🇳🇪" },
  Nigeria: { slug: "Nigerian_citizens", emoji: "🇳🇬" },
  "North Korea": { slug: "North_Korean_citizens", emoji: "🇰🇵" },
  "North Macedonia": { slug: "Macedonian_citizens", emoji: "🇲🇰" },
  Norway: { slug: "Norwegian_citizens", emoji: "🇳🇴" },
  Oman: { slug: "Omani_citizens", emoji: "🇴🇲" },
  Pakistan: { slug: "Pakistani_citizens", emoji: "🇵🇰" },
  Palau: { slug: "Palauan_citizens", emoji: "🇵🇼" },
  Palestine: { slug: "Palestinian_citizens", emoji: "🇵🇸" },
  Panama: { slug: "Panamanian_citizens", emoji: "🇵🇦" },
  "Papua New Guinea": { slug: "Papua_New_Guinean_citizens", emoji: "🇵🇬" },
  Paraguay: { slug: "Paraguayan_citizens", emoji: "🇵🇾" },
  Peru: { slug: "Peruvian_citizens", emoji: "🇵🇪" },
  Philippines: { slug: "Filipino_citizens", emoji: "🇵🇭" },
  Poland: { slug: "Polish_citizens", emoji: "🇵🇱" },
  Portugal: { slug: "Portuguese_citizens", emoji: "🇵🇹" },
  Qatar: { slug: "Qatari_citizens", emoji: "🇶🇦" },
  Romania: { slug: "Romanian_citizens", emoji: "🇷🇴" },
  Russia: { slug: "Russian_citizens", emoji: "🇷🇺" },
  Rwanda: { slug: "Rwandan_citizens", emoji: "🇷🇼" },
  "Saint Kitts and Nevis": { slug: "Kittitian_citizens", emoji: "🇰🇳" },
  "Saint Lucia": { slug: "Saint_Lucian_citizens", emoji: "🇱🇨" },
  "Saint Vincent and the Grenadines": {
    slug: "Vincentian_citizens",
    emoji: "🇻🇨",
  },
  Samoa: { slug: "Samoan_citizens", emoji: "🇼🇸" },
  "San Marino": { slug: "Sammarinese_citizens", emoji: "🇸🇲" },
  "São Tomé and Príncipe": { slug: "Sao_Tomean_citizens", emoji: "🇸🇹" },
  "Saudi Arabia": { slug: "Saudi_citizens", emoji: "🇸🇦" },
  Senegal: { slug: "Senegalese_citizens", emoji: "🇸🇳" },
  Serbia: { slug: "Serbian_citizens", emoji: "🇷🇸" },
  Seychelles: { slug: "Seychellois_citizens", emoji: "🇸🇨" },
  "Sierra Leone": { slug: "Sierra_Leonean_citizens", emoji: "🇸🇱" },
  Singapore: { slug: "Singaporean_citizens", emoji: "🇸🇬" },
  Slovakia: { slug: "Slovak_citizens", emoji: "🇸🇰" },
  Slovenia: { slug: "Slovenian_citizens", emoji: "🇸🇮" },
  "Solomon Islands": { slug: "Solomon_Islander_citizens", emoji: "🇸🇧" },
  Somalia: { slug: "Somali_citizens", emoji: "🇸🇴" },
  "South Africa": { slug: "South_African_citizens", emoji: "🇿🇦" },
  "South Korea": { slug: "South_Korean_citizens", emoji: "🇰🇷" },
  "South Sudan": { slug: "South_Sudanese_citizens", emoji: "🇸🇸" },
  Spain: { slug: "Spanish_citizens", emoji: "🇪🇸" },
  "Sri Lanka": { slug: "Sri_Lankan_citizens", emoji: "🇱🇰" },
  Sudan: { slug: "Sudanese_citizens", emoji: "🇸🇩" },
  Suriname: { slug: "Surinamese_citizens", emoji: "🇸🇷" },
  Sweden: { slug: "Swedish_citizens", emoji: "🇸🇪" },
  Switzerland: { slug: "Swiss_citizens", emoji: "🇨🇭" },
  Syria: { slug: "Syrian_citizens", emoji: "🇸🇾" },
  Tajikistan: { slug: "Tajik_citizens", emoji: "🇹🇯" },
  Tanzania: { slug: "Tanzanian_citizens", emoji: "🇹🇿" },
  Thailand: { slug: "Thai_citizens", emoji: "🇹🇭" },
  "Timor-Leste": { slug: "Timorese_citizens", emoji: "🇹🇱" },
  Togo: { slug: "Togolese_citizens", emoji: "🇹🇬" },
  Tonga: { slug: "Tongan_citizens", emoji: "🇹🇴" },
  "Trinidad and Tobago": {
    slug: "Trinidadian_and_Tobagonian_citizens",
    emoji: "🇹🇹",
  },
  Tunisia: { slug: "Tunisian_citizens", emoji: "🇹🇳" },
  Turkey: { slug: "Turkish_citizens", emoji: "🇹🇷" },
  Turkmenistan: { slug: "Turkmen_citizens", emoji: "🇹🇲" },
  Tuvalu: { slug: "Tuvaluan_citizens", emoji: "🇹🇻" },
  Uganda: { slug: "Ugandan_citizens", emoji: "🇺🇬" },
  Ukraine: { slug: "Ukrainian_citizens", emoji: "🇺🇦" },
  "United Arab Emirates": { slug: "Emirati_citizens", emoji: "🇦🇪" },
  "United Kingdom": { slug: "British_citizens", emoji: "🇬🇧" },
  "United States": { slug: "United_States_citizens", emoji: "🇺🇸" },
  Uruguay: { slug: "Uruguayan_citizens", emoji: "🇺🇾" },
  Uzbekistan: { slug: "Uzbek_citizens", emoji: "🇺🇿" },
  Vanuatu: { slug: "Ni-Vanuatu_citizens", emoji: "🇻🇺" },
  "Vatican City": { slug: "Vatican_citizens", emoji: "🇻🇦" },
  Venezuela: { slug: "Venezuelan_citizens", emoji: "🇻🇪" },
  Vietnam: { slug: "Vietnamese_citizens", emoji: "🇻🇳" },
  Yemen: { slug: "Yemeni_citizens", emoji: "🇾🇪" },
  Zambia: { slug: "Zambian_citizens", emoji: "🇿🇲" },
  Zimbabwe: { slug: "Zimbabwean_citizens", emoji: "🇿🇼" },
  Kosovo: { slug: "Kosovar_citizens", emoji: "🇽🇰" },
  Taiwan: { slug: "Taiwanese_citizens", emoji: "🇹🇼" },
};

export default countryMeta;
