const visaData = [
  {
    passport_country: "France",
    destination_country: "Afghanistan",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Albania",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Algeria",
    visa_requirement: "E-visa",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Andorra",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Angola",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Antigua and Barbuda",
    visa_requirement: "Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "France",
    destination_country: "Argentina",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Armenia",
    visa_requirement: "Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "France",
    destination_country: "Australia",
    visa_requirement: "eVisitor",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Austria",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Azerbaijan",
    visa_requirement: "eVisa",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Bahamas",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Bahrain",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "14 days",
  },
  {
    passport_country: "France",
    destination_country: "Bangladesh",
    visa_requirement: "Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Barbados",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Belarus",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Belgium",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Belize",
    visa_requirement: "Visa not required",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Benin",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Bhutan",
    visa_requirement: "eVisa",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Bolivia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Bosnia and Herzegovina",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Botswana",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Brazil",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Brunei",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Bulgaria",
    visa_requirement: "Freedom of movement",
    notes: "Unlimited stay",
  },
  {
    passport_country: "France",
    destination_country: "Burkina Faso",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Burundi",
    visa_requirement: "Online visa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Cambodia",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Cameroon",
    visa_requirement: "eVisa",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Canada",
    visa_requirement: "eTA / Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "France",
    destination_country: "Cape Verde",
    visa_requirement: "EASE",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Central African Republic",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Chad",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Chile",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "China",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Colombia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Comoros",
    visa_requirement: "Visa on arrival",
    notes: "45 days",
  },
  {
    passport_country: "France",
    destination_country: "Republic of the Congo",
    visa_requirement: "E-visa",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Democratic Republic of the Congo",
    visa_requirement: "eVisa",
    notes: "7 days",
  },
  {
    passport_country: "France",
    destination_country: "Costa Rica",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Côte d'Ivoire",
    visa_requirement: "eVisa",
    notes: "3 months",
  },
  {
    passport_country: "France",
    destination_country: "Croatia",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Cuba",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Cyprus",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Czech Republic",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Denmark",
    visa_requirement: "Freedom of movement (in mainland Denmark)",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Djibouti",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Dominica",
    visa_requirement: "Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "France",
    destination_country: "Dominican Republic",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Ecuador",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Egypt",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "El Salvador",
    visa_requirement: "Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "France",
    destination_country: "Equatorial Guinea",
    visa_requirement: "eVisa",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Eritrea",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Estonia",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Eswatini",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Ethiopia",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Fiji",
    visa_requirement: "Visa not required",
    notes: "120 days",
  },
  {
    passport_country: "France",
    destination_country: "Finland",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Gabon",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Gambia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Georgia",
    visa_requirement: "Visa not required",
    notes: "1 year",
  },
  {
    passport_country: "France",
    destination_country: "Germany",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Ghana",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Greece",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Grenada",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Guatemala",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Guinea",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Guinea-Bissau",
    visa_requirement: "Visa on arrival",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Guyana",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Haiti",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Honduras",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Hungary",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Iceland",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "India",
    visa_requirement: "eVisa",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Indonesia",
    visa_requirement: "e-VOA / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Iran",
    visa_requirement: "eVisa",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Iraq",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "60 days",
  },
  {
    passport_country: "France",
    destination_country: "Ireland",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Israel",
    visa_requirement: "ETA-IL",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Italy",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Jamaica",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Japan",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Jordan",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Kazakhstan",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Kenya",
    visa_requirement: "Electronic Travel Authorisation",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Kiribati",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Kosovo",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "North Korea",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "South Korea",
    visa_requirement: "Electronic Travel Authorization",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Kuwait",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Kyrgyzstan",
    visa_requirement: "Visa not required",
    notes: "60 days",
  },
  {
    passport_country: "France",
    destination_country: "Laos",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Latvia",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Lebanon",
    visa_requirement: "Free visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Lesotho",
    visa_requirement: "Visa not required",
    notes: "14 days",
  },
  {
    passport_country: "France",
    destination_country: "Liberia",
    visa_requirement: "E-visa",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Libya",
    visa_requirement: "eVisa",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Liechtenstein",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Lithuania",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Luxembourg",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Madagascar",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "60 days",
  },
  {
    passport_country: "France",
    destination_country: "Malawi",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Malaysia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Maldives",
    visa_requirement: "Free visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Mali",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Malta",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Marshall Islands",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Mauritania",
    visa_requirement: "eVisa",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Mauritius",
    visa_requirement: "Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "France",
    destination_country: "Mexico",
    visa_requirement: "Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "France",
    destination_country: "Micronesia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Moldova",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Monaco",
    visa_requirement: "Visa not required",
    notes: "3 months",
  },
  {
    passport_country: "France",
    destination_country: "Mongolia",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Montenegro",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Morocco",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Mozambique",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Myanmar",
    visa_requirement: "eVisa",
    notes: "28 days",
  },
  {
    passport_country: "France",
    destination_country: "Namibia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Nauru",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Nepal",
    visa_requirement: "Online Visa / Visa on arrival",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Netherlands",
    visa_requirement: "Freedom of movement (European Netherlands)",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "New Zealand",
    visa_requirement: "NZeTA",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Nicaragua",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Niger",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Nigeria",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "North Macedonia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Norway",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Oman",
    visa_requirement: "Visa not required / eVisa",
    notes: "14 days / 30 days",
  },
  {
    passport_country: "France",
    destination_country: "Pakistan",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Palau",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Panama",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Papua New Guinea",
    visa_requirement: "Easy Visitor Permit",
    notes: "60 days",
  },
  {
    passport_country: "France",
    destination_country: "Paraguay",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Peru",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Philippines",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Poland",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Portugal",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Qatar",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Romania",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Russia",
    visa_requirement: "eVisa",
    notes: "16 days",
  },
  {
    passport_country: "France",
    destination_country: "Rwanda",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Saint Kitts and Nevis",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Saint Lucia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Saint Vincent and the Grenadines",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Samoa",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "San Marino",
    visa_requirement: "Visa not required",
    notes: "3 months",
  },
  {
    passport_country: "France",
    destination_country: "São Tomé and Príncipe",
    visa_requirement: "Visa not required",
    notes: "15 days",
  },
  {
    passport_country: "France",
    destination_country: "Saudi Arabia",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Senegal",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Serbia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Seychelles",
    visa_requirement: "Visa not required",
    notes: "3 months",
  },
  {
    passport_country: "France",
    destination_country: "Sierra Leone",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "3 months / 30 days",
  },
  {
    passport_country: "France",
    destination_country: "Singapore",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Slovakia",
    visa_requirement: "Freedom of movement",
    notes: "Unlimited stay",
  },
  {
    passport_country: "France",
    destination_country: "Slovenia",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Solomon Islands",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Somalia",
    visa_requirement: "eVisa",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "South Africa",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "South Sudan",
    visa_requirement: "eVisa",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Spain",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Sri Lanka",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Sudan",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Suriname",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Sweden",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Switzerland",
    visa_requirement: "Freedom of movement",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Syria",
    visa_requirement: "eVisa",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Tajikistan",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Tanzania",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Thailand",
    visa_requirement: "Visa not required",
    notes: "60 days",
  },
  {
    passport_country: "France",
    destination_country: "Timor-Leste",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Togo",
    visa_requirement: "eVisa",
    notes: "15 days",
  },
  {
    passport_country: "France",
    destination_country: "Tonga",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Trinidad and Tobago",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Tunisia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Turkey",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Turkmenistan",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Tuvalu",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Uganda",
    visa_requirement: "eVisa",
    notes: "3 months",
  },
  {
    passport_country: "France",
    destination_country: "Ukraine",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "United Arab Emirates",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "United Kingdom",
    visa_requirement: "Visa not required",
    notes: "6 months",
  },
  {
    passport_country: "France",
    destination_country: "United States",
    visa_requirement: "Visa Waiver Program",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Uruguay",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Uzbekistan",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "France",
    destination_country: "Vanuatu",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Vatican City",
    visa_requirement: "Visa not required",
    notes: "1 day",
  },
  {
    passport_country: "France",
    destination_country: "Venezuela",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Vietnam",
    visa_requirement: "Visa not required",
    notes: "45 days",
  },
  {
    passport_country: "France",
    destination_country: "Yemen",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "France",
    destination_country: "Zambia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "France",
    destination_country: "Zimbabwe",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Afghanistan",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Albania",
    visa_requirement: "Visa not required",
    notes: "1 year",
  },
  {
    passport_country: "United States",
    destination_country: "Algeria",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Andorra",
    visa_requirement: "Visa not required",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Angola",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Antigua and Barbuda",
    visa_requirement: "Visa not required",
    notes: "6 months",
  },
  {
    passport_country: "United States",
    destination_country: "Argentina",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Armenia",
    visa_requirement: "Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "United States",
    destination_country: "Australia",
    visa_requirement: "Electronic Travel Authority",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Austria",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Azerbaijan",
    visa_requirement: "eVisa / Visa on arrival (conditional)",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Bahamas",
    visa_requirement: "Visa not required",
    notes: "8 months",
  },
  {
    passport_country: "United States",
    destination_country: "Bahrain",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "14 days",
  },
  {
    passport_country: "United States",
    destination_country: "Bangladesh",
    visa_requirement: "Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Barbados",
    visa_requirement: "Visa not required",
    notes: "6 months",
  },
  {
    passport_country: "United States",
    destination_country: "Belarus",
    visa_requirement: "eVisa",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Belgium",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Belize",
    visa_requirement: "Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "United States",
    destination_country: "Benin",
    visa_requirement: "eVisa",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Bhutan",
    visa_requirement: "eVisa",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Bolivia",
    visa_requirement: "Online Visa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Bosnia and Herzegovina",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Botswana",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Brazil",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Brunei",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Bulgaria",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Burkina Faso",
    visa_requirement: "eVisa",
    notes: "1 month",
  },
  {
    passport_country: "United States",
    destination_country: "Burundi",
    visa_requirement: "Online Visa / Visa on arrival",
    notes: "1 month",
  },
  {
    passport_country: "United States",
    destination_country: "Cambodia",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Cameroon",
    visa_requirement: "eVisa",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Canada",
    visa_requirement: "Visa not required",
    notes: "6 months",
  },
  {
    passport_country: "United States",
    destination_country: "Cape Verde",
    visa_requirement: "EASE",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Central African Republic",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Chad",
    visa_requirement: "Admission suspended",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Chile",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "China",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Colombia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Comoros",
    visa_requirement: "Visa on arrival",
    notes: "45 days",
  },
  {
    passport_country: "United States",
    destination_country: "Republic of the Congo",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Democratic Republic of the Congo",
    visa_requirement: "eVisa",
    notes: "7 days",
  },
  {
    passport_country: "United States",
    destination_country: "Costa Rica",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Côte d'Ivoire",
    visa_requirement: "eVisa",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Croatia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Cuba",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Cyprus",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Czech Republic",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Denmark",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Djibouti",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Dominica",
    visa_requirement: "Visa not required",
    notes: "6 months",
  },
  {
    passport_country: "United States",
    destination_country: "Dominican Republic",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Ecuador",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Egypt",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "El Salvador",
    visa_requirement: "Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "United States",
    destination_country: "Equatorial Guinea",
    visa_requirement: "eVisa",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Eritrea",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Estonia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Eswatini",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Ethiopia",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "up to 90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Fiji",
    visa_requirement: "Visa not required",
    notes: "4 months",
  },
  {
    passport_country: "United States",
    destination_country: "Finland",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "France",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Gabon",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Gambia",
    visa_requirement: "Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Georgia",
    visa_requirement: "Visa not required",
    notes: "1 year",
  },
  {
    passport_country: "United States",
    destination_country: "Germany",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Ghana",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Greece",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Grenada",
    visa_requirement: "Visa not required",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Guatemala",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Guinea",
    visa_requirement: "eVisa",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Guinea-Bissau",
    visa_requirement: "Visa on arrival",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Guyana",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Haiti",
    visa_requirement: "Visa not required",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Honduras",
    visa_requirement: "Visa not required",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Hungary",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Iceland",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "India",
    visa_requirement: "eVisa",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Indonesia",
    visa_requirement: "e-VOA / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Iran",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Iraq",
    visa_requirement: "eVisa",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Ireland",
    visa_requirement: "Visa not required",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Israel",
    visa_requirement: "Electronic Travel Authorization",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Italy",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Jamaica",
    visa_requirement: "Visa not required",
    notes: "6 months",
  },
  {
    passport_country: "United States",
    destination_country: "Japan",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Jordan",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Kazakhstan",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Kenya",
    visa_requirement: "Electronic Travel Authorisation",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Kiribati",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "North Korea",
    visa_requirement: "Travel restricted by U.S. government",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "South Korea",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Kuwait",
    visa_requirement: "eVisa / Free Visa on arrival",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Kyrgyzstan",
    visa_requirement: "Visa not required",
    notes: "60 days",
  },
  {
    passport_country: "United States",
    destination_country: "Laos",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Latvia",
    visa_requirement: "Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "United States",
    destination_country: "Lebanon",
    visa_requirement: "Free visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Lesotho",
    visa_requirement: "Visa not required",
    notes: "14 days",
  },
  {
    passport_country: "United States",
    destination_country: "Liberia",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Libya",
    visa_requirement: "eVisa",
    notes: "30 Days",
  },
  {
    passport_country: "United States",
    destination_country: "Liechtenstein",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Lithuania",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Luxembourg",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Madagascar",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "60 days",
  },
  {
    passport_country: "United States",
    destination_country: "Malawi",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Malaysia",
    visa_requirement: "Visa not required",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Maldives",
    visa_requirement: "Free visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Mali",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Malta",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Marshall Islands",
    visa_requirement: "Visa not required",
    notes: "Unlimited",
  },
  {
    passport_country: "United States",
    destination_country: "Mauritania",
    visa_requirement: "eVisa",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Mauritius",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Mexico",
    visa_requirement: "Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "United States",
    destination_country: "Micronesia",
    visa_requirement: "Visa not required",
    notes: "365 days",
  },
  {
    passport_country: "United States",
    destination_country: "Moldova",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Monaco",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Mongolia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Montenegro",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Morocco",
    visa_requirement: "Visa not required",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Mozambique",
    visa_requirement: "Electronic Travel Authorization",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Myanmar",
    visa_requirement: "eVisa",
    notes: "28 days",
  },
  {
    passport_country: "United States",
    destination_country: "Namibia",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Nauru",
    visa_requirement: "Visa required",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Nepal",
    visa_requirement: "Online Visa / Visa on arrival",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Netherlands",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "New Zealand",
    visa_requirement: "Electronic Travel Authority",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Nicaragua",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Niger",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Nigeria",
    visa_requirement: "eVisa",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "North Macedonia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Norway",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Oman",
    visa_requirement: "Visa not required / eVisa",
    notes: "14 days / 30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Pakistan",
    visa_requirement: "Free eVisa",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Palau",
    visa_requirement: "Visa not required",
    notes: "1 year",
  },
  {
    passport_country: "United States",
    destination_country: "Panama",
    visa_requirement: "Visa not required",
    notes: "180 days",
  },
  {
    passport_country: "United States",
    destination_country: "Papua New Guinea",
    visa_requirement: "eVisa",
    notes: "60 days",
  },
  {
    passport_country: "United States",
    destination_country: "Paraguay",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Peru",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Philippines",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Poland",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Portugal",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Qatar",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Romania",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Russia",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Rwanda",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Saint Kitts and Nevis",
    visa_requirement: "Visa not required",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Saint Lucia",
    visa_requirement: "Visa not required",
    notes: "6 weeks",
  },
  {
    passport_country: "United States",
    destination_country: "Saint Vincent and the Grenadines",
    visa_requirement: "Visa not required",
    notes: "6 months",
  },
  {
    passport_country: "United States",
    destination_country: "Samoa",
    visa_requirement: "Entry permit on arrival",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "San Marino",
    visa_requirement: "Visa not required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "São Tomé and Príncipe",
    visa_requirement: "Visa not required",
    notes: "15 days",
  },
  {
    passport_country: "United States",
    destination_country: "Saudi Arabia",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Senegal",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Serbia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Seychelles",
    visa_requirement: "Electronic Border System",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Sierra Leone",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "3 months / 30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Singapore",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Slovakia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Slovenia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Solomon Islands",
    visa_requirement: "Free Visitor's permit on arrival",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Somalia",
    visa_requirement: "eVisa",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "South Africa",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "South Sudan",
    visa_requirement: "eVisa",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Spain",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Sri Lanka",
    visa_requirement: "ETA / Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Sudan",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Suriname",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Sweden",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Switzerland",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Syria",
    visa_requirement: "eVisa",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Tajikistan",
    visa_requirement: "Visa not required / eVisa",
    notes: "30 days / 60 days",
  },
  {
    passport_country: "United States",
    destination_country: "Tanzania",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Thailand",
    visa_requirement: "Visa not required",
    notes: "60 days",
  },
  {
    passport_country: "United States",
    destination_country: "Timor-Leste",
    visa_requirement: "Visa on arrival",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Togo",
    visa_requirement: "eVisa",
    notes: "15 days",
  },
  {
    passport_country: "United States",
    destination_country: "Tonga",
    visa_requirement: "Free visa on arrival",
    notes: "31 days",
  },
  {
    passport_country: "United States",
    destination_country: "Trinidad and Tobago",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Tunisia",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Turkey",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Turkmenistan",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Tuvalu",
    visa_requirement: "Visa on arrival",
    notes: "1 month",
  },
  {
    passport_country: "United States",
    destination_country: "Uganda",
    visa_requirement: "eVisa",
    notes: "3 months",
  },
  {
    passport_country: "United States",
    destination_country: "Ukraine",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "United Arab Emirates",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "United Kingdom",
    visa_requirement: "Electronic Travel Authorisation",
    notes: "6 months",
  },
  {
    passport_country: "United States",
    destination_country: "Uruguay",
    visa_requirement: "Visa not required",
    notes: "90 days",
  },
  {
    passport_country: "United States",
    destination_country: "Uzbekistan",
    visa_requirement: "Visa not required (conditional) / eVisa",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Vanuatu",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Vatican City",
    visa_requirement: "Visa not required",
    notes: "N/A",
  },
  {
    passport_country: "United States",
    destination_country: "Venezuela",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Vietnam",
    visa_requirement: "eVisa",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Yemen",
    visa_requirement: "Visa required",
    notes: "",
  },
  {
    passport_country: "United States",
    destination_country: "Zambia",
    visa_requirement: "Visa not required",
    notes: "30 days",
  },
  {
    passport_country: "United States",
    destination_country: "Zimbabwe",
    visa_requirement: "eVisa / Visa on arrival",
    notes: "1 month",
  },
];

export default visaData;
